package com.anushaporter.backend;

import com.anushaporter.backend.model.Driver;
import com.anushaporter.backend.model.Order;
import com.anushaporter.backend.repository.DriverRepository;
import com.anushaporter.backend.repository.OrderRepository;
import com.anushaporter.backend.util.JwtUtil;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Primary;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;
import software.amazon.awssdk.services.s3.S3Client;

import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(classes = BackendApplication.class)
@Import(DriverAndDeliveryOtpVerificationTest.TestConfig.class)
public class DriverAndDeliveryOtpVerificationTest {

    @TestConfiguration
    static class TestConfig {
        @Bean
        @Primary
        public S3Client mockS3Client() {
            return Mockito.mock(S3Client.class);
        }
    }

    @Autowired
    private WebApplicationContext webApplicationContext;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private DriverRepository driverRepository;

    @Autowired
    private JwtUtil jwtUtil;

    private MockMvc mockMvc;

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext).build();
        orderRepository.deleteAll();
        driverRepository.deleteAll();
    }

    @Test
    void testDeliveryOtpEndpoints_ReturnOtpAndDeliveryOtpAcrossAllRouteAliases() throws Exception {
        String bookingId = "BK-OTP-TEST-001";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("user@example.com");
        order.setServiceName("Tata Ace");
        order.setStatus("assigned");
        order.setDeliveryOtp("7291");
        orderRepository.save(order);

        // 1. GET /api/bookings/{id}/delivery-otp
        mockMvc.perform(get("/api/bookings/" + bookingId + "/delivery-otp"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.bookingId", is(bookingId)))
                .andExpect(jsonPath("$.otp", is("7291")))
                .andExpect(jsonPath("$.deliveryOtp", is("7291")))
                .andExpect(jsonPath("$.data.otp", is("7291")))
                .andExpect(jsonPath("$.data.deliveryOtp", is("7291")));

        // 2. GET /api/orders/{id}/delivery-otp
        mockMvc.perform(get("/api/orders/" + bookingId + "/delivery-otp"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.otp", is("7291")))
                .andExpect(jsonPath("$.deliveryOtp", is("7291")));

        // 3. GET /api/bookings/{id}/otp
        mockMvc.perform(get("/api/bookings/" + bookingId + "/otp"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.otp", is("7291")))
                .andExpect(jsonPath("$.deliveryOtp", is("7291")));

        // 4. GET /api/orders/{id}/otp
        mockMvc.perform(get("/api/orders/" + bookingId + "/otp"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.otp", is("7291")))
                .andExpect(jsonPath("$.deliveryOtp", is("7291")));
    }

    @Test
    void testDeliveryOtp_AutoGeneratedIfNullWhenRequested() throws Exception {
        String bookingId = "BK-OTP-NULL-002";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("user@example.com");
        order.setServiceName("Tata Ace");
        order.setStatus("assigned");
        order.setDeliveryOtp(null); // No OTP initially
        orderRepository.save(order);

        // Querying delivery-otp must auto-generate, persist and return it
        mockMvc.perform(get("/api/bookings/" + bookingId + "/delivery-otp"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.otp", notNullValue()))
                .andExpect(jsonPath("$.deliveryOtp", notNullValue()));

        Order refreshed = orderRepository.findByBookingId(bookingId).orElseThrow();
        assertNotNull(refreshed.getDeliveryOtp());
        assertEquals(4, refreshed.getDeliveryOtp().length());
    }

    @Test
    void testLiveTracking_ReturnsRealAssignedDriverProfile_InsteadOfManjunath() throws Exception {
        // Create actual Driver in DB
        Driver driver = new Driver();
        driver.setName("Suresh Varma");
        driver.setEmail("suresh@driver.com");
        driver.setPhone("9848012345");
        driver.setVehicleNumber("TS 09 XY 9999");
        driver.setVehicleType("Tata Ace");
        driver.setRating("4.9");
        driver.setStatus("online");
        driver = driverRepository.save(driver);

        String bookingId = "PM-TEST-003";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("user@example.com");
        order.setServiceName("Packers & Movers - 1 BHK");
        order.setGoodsCategory("Household Goods");
        order.setStatus("assigned");
        order.setDeliveryOtp("4819");
        order.setDriverId(driver.getId().toString());
        order.setDriverName(driver.getName());
        order.setDriverPhone(driver.getPhone());
        order.setDriverVehicleNumber(driver.getVehicleNumber());
        orderRepository.save(order);

        // GET /api/bookings/{id}/tracking
        mockMvc.perform(get("/api/bookings/" + bookingId + "/tracking"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.bookingId", is(bookingId)))
                .andExpect(jsonPath("$.otp", is("4819")))
                .andExpect(jsonPath("$.deliveryOtp", is("4819")))
                // Ensure driver name is Suresh Varma, NOT "Manjunath (Supervisor)"
                .andExpect(jsonPath("$.driver.name", is("Suresh Varma")))
                .andExpect(jsonPath("$.driver.name", not(containsString("Supervisor"))))
                .andExpect(jsonPath("$.driver.phone", is("9848012345")))
                .andExpect(jsonPath("$.driver.vehicleNumber", is("TS 09 XY 9999")))
                .andExpect(jsonPath("$.assignedDriver.name", is("Suresh Varma")))
                .andExpect(jsonPath("$.driverInfo.name", is("Suresh Varma")));
    }

    @Test
    void testBookingDetail_ReturnsRealAssignedDriverProfileAndOtp() throws Exception {
        Driver driver = new Driver();
        driver.setName("Vikram Reddy");
        driver.setEmail("vikram@driver.com");
        driver.setPhone("9876500000");
        driver.setVehicleNumber("AP 28 AB 5555");
        driver.setVehicleType("Pickup 8ft");
        driver.setRating("4.8");
        driver.setStatus("online");
        driver = driverRepository.save(driver);

        String bookingId = "BK-DETAIL-004";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("customer@example.com");
        order.setServiceName("Pickup 8ft");
        order.setStatus("assigned");
        order.setDeliveryOtp("9314");
        order.setDriverId(driver.getId().toString());
        order.setDriverName(driver.getName());
        order.setDriverPhone(driver.getPhone());
        order.setDriverVehicleNumber(driver.getVehicleNumber());
        orderRepository.save(order);

        String token = jwtUtil.generateToken("customer@example.com");

        // GET /api/bookings/{id}
        mockMvc.perform(get("/api/bookings/" + bookingId)
                .header("Authorization", "Bearer " + token))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.bookingId", is(bookingId)))
                .andExpect(jsonPath("$.otp", is("9314")))
                .andExpect(jsonPath("$.deliveryOtp", is("9314")))
                .andExpect(jsonPath("$.driver.name", is("Vikram Reddy")))
                .andExpect(jsonPath("$.assignedDriver.name", is("Vikram Reddy")))
                .andExpect(jsonPath("$.driverInfo.name", is("Vikram Reddy")))
                .andExpect(jsonPath("$.driver.phone", is("9876500000")));
    }

    @Test
    void testLiveTracking_UnassignedPackersDemo_FallsBackToSupervisor() throws Exception {
        String bookingId = "PM-DEMO-UNASSIGNED-005";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("user@example.com");
        order.setServiceName("Packers & Movers - 2 BHK");
        order.setGoodsCategory("Household");
        order.setStatus("searching");
        order.setDeliveryOtp("1234");
        // No driver assigned
        order.setDriverId(null);
        order.setDriverName(null);
        orderRepository.save(order);

        // When unassigned, should maintain backwards-compatible fallback for demo
        mockMvc.perform(get("/api/bookings/" + bookingId + "/tracking"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.driver.name", containsString("Supervisor")));
    }

    @Test
    void testCancellationAllowed_WhilePlacingOrderAndInTransit() throws Exception {
        String bookingId = "BK-CANCEL-TEST-001";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("customer@example.com");
        order.setServiceName("2 Wheeler");
        order.setStatus("searching");
        order.setDeliveryOtp("5555");
        orderRepository.save(order);

        // 1. Verify tracking exposes canCancel: true while placing order / searching
        mockMvc.perform(get("/api/bookings/" + bookingId + "/tracking"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.canCancel", is(true)))
                .andExpect(jsonPath("$.isCancellable", is(true)));

        // 2. Perform cancellation via PUT
        mockMvc.perform(put("/api/bookings/" + bookingId + "/cancel")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"reason\": \"Changed mind\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success", is(true)))
                .andExpect(jsonPath("$.status", is("cancelled")));

        // Verify DB status
        Order cancelledOrder = orderRepository.findByBookingId(bookingId).orElseThrow();
        assertEquals("cancelled", cancelledOrder.getStatus());
    }

    @Test
    void testCancellationBlocked_WhenDriverArrivedAtDropLocation() throws Exception {
        String bookingId = "BK-CANCEL-TEST-002";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("customer@example.com");
        order.setServiceName("Tata Ace");
        order.setStatus("driver_reached");
        order.setDeliveryOtp("7777");
        orderRepository.save(order);

        // 1. Tracking must show canCancel: false
        mockMvc.perform(get("/api/bookings/" + bookingId + "/tracking"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.canCancel", is(false)))
                .andExpect(jsonPath("$.isCancellable", is(false)))
                .andExpect(jsonPath("$.cancellationBlockedReason", notNullValue()));

        // 2. Attempting to cancel must return 400 Bad Request
        mockMvc.perform(put("/api/bookings/" + bookingId + "/cancel")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"reason\": \"Want to cancel\"}"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success", is(false)))
                .andExpect(jsonPath("$.error", is("CANCELLATION_WINDOW_EXPIRED")))
                .andExpect(jsonPath("$.canCancel", is(false)));
    }

    @Test
    void testCancellationBlocked_WhenDriverGpsWithin300MetersOfDrop() throws Exception {
        Driver driver = new Driver();
        driver.setName("Proximity Driver");
        driver.setEmail("prox@driver.com");
        driver.setPhone("9988776655");
        driver.setLatitude(17.4402);
        driver.setLongitude(78.3802);
        driver = driverRepository.save(driver);

        String bookingId = "BK-CANCEL-TEST-003";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("customer@example.com");
        order.setServiceName("Tata Ace");
        order.setStatus("in_transit");
        order.setDriverId(driver.getId().toString());
        order.setDropLat(17.4400); // Distance is ~30 meters!
        order.setDropLng(78.3800);
        orderRepository.save(order);

        // Tracking must show canCancel: false due to proximity
        mockMvc.perform(get("/api/bookings/" + bookingId + "/tracking"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.canCancel", is(false)));

        // Attempting to cancel must return 400 Bad Request
        mockMvc.perform(post("/api/bookings/" + bookingId + "/cancel")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"reason\": \"Too late cancel\"}"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success", is(false)))
                .andExpect(jsonPath("$.error", is("CANCELLATION_WINDOW_EXPIRED")));
    }

    @Test
    void testCancellationBlocked_WhenOtpVerifiedOrDelivered() throws Exception {
        String bookingId = "BK-CANCEL-TEST-004";
        Order order = new Order();
        order.setBookingId(bookingId);
        order.setUserEmail("customer@example.com");
        order.setServiceName("Tata Ace");
        order.setStatus("in_transit");
        order.setOtpVerified(true);
        orderRepository.save(order);

        // Attempting to cancel must return 400 Bad Request
        mockMvc.perform(put("/api/bookings/" + bookingId + "/cancel"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success", is(false)))
                .andExpect(jsonPath("$.error", is("CANCELLATION_WINDOW_EXPIRED")));
    }
}
