server.port=8080

# Database Configuration
# Defaults to H2 if environment variables are not provided
spring.datasource.url=${RDS_URL:jdbc:h2:file:./data/anushadb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}
spring.datasource.username=${RDS_USERNAME:sa}
spring.datasource.password=${RDS_PASSWORD:password}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# AWS Configuration
aws.s3.bucket.name=${S3_BUCKET_NAME:anusha-porter-app-images}

# Enable CORS for development
spring.web.cors.allowed-origins=*

# Email Configuration (Update with your real Gmail details)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anushaporter@gmail.com
spring.mail.password=uaiicjknrnjdybve
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.address=0.0.0.0
google.maps.api.key=AIzaSyBMZfGGMXsIOZYBpCRW7lVpPVhaRQnAnjo

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
server.ssl.enabled=${ENABLE_SSL:false}
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=pkcs12
